Script started on Fri 01 May 2015 09:04:36 PM PDT
~
hkwan003@hammer $ cd CS100/
~/CS100
hkwan003@hammer $ ls
[0m[01;34mLab1[0m/  [01;34mLab2[0m/  [01;34mLab3[0m/  [01;34mrshell[0m/
[m~/CS100
hkwan003@hammer $ cd R[Krshell/
~/CS100/rshell
hkwan003@hammer $ ls
[0m[01;34mbin[0m/  LICENSE  Makefile  README.md  [01;34msrc[0m/  [01;34mtests[0m/
[m~/CS100/rshell
hkwan003@hammer $ cd s[Ktests/[K[K[K[K[K[K[K[K[Kmake
mkdir -p ./bin
g++  ./src/ls.cpp -o ./bin/ls
~/CS100/rshell
hkwan003@hammer $ bin/ls -a
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls 
Nothing passed in to argv.
~/CS100/rshell
hkwan003@hammer $ bin/ls -R
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls -
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ A[Kbin/ls -A[KalR
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls -la
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls #nothing else works but ls -a
Nothing passed in to argv.
~/CS100/rshell
hkwan003@hammer $ bin/ls #at least it is in alpa[Khabetica lo[K[K[Kl order
Nothing passed in to argv.
~/CS100/rshell
hkwan003@hammer $ bin/ls #starting[K[K[K[K[K[K[K[K[K-A[Ka src
. .. .git bin LICENSE Makefile README.md src tests . . .. .. .git .git bin bin LICENSE LICENSE Makefile Makefile README.md README.md src src tests tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls -[K`[K~
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ bin/ls a[K-s #[K[K[Ka any[K[K[K#any t[Ks[Karugment makes it output ls-a
. .. .git bin LICENSE Makefile README.md src tests 
~/CS100/rshell
hkwan003@hammer $ exit
exit

Script done on Fri 01 May 2015 09:06:22 PM PDT
